name: Build and test 🏗🧪

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: echo "Installing dependencies ⌛️"
    - run: npm ci
    - run: npm i knex
    - run: echo "Building the client 🧱"
    - run: npm run build --if-present
    - run: echo "Linting the code 👀"
    - run: npm run lint
    - run: echo "Running the tests 🧪"
    - run: sudo systemctl start mysql.service
    - run: sudo mysql -e 'DROP DATABASE IF EXISTS deployer;' -proot
    - run: sudo mysql -e 'CREATE DATABASE deployer;' -proot
    - run: npx knex migrate:latest
    - run: npm test
